appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: APphAv9SygSWgIXFD59tG5So/LgJLVD4XixApKSWtkC1OzwqzLeovt6/uO6I6KrbHyPJOZMmFdmrVxpfHERqWUPVi116Gckxa+Q6c67AqvZNBv1FJII/Zfkyr5U6D39q2sK1cTfEC8Cj+E1uAmT3o1DPJoAcLdttIK6kiJtg5mYw0V/9r8htOKd7QWn73l00QhiNU6iraMHa5Fv69lyHM7JXdClsAadVnx7W0e4qQY9e8fu2vaNmPZPzM9X7WipIS7nk7NA3GT0GehhGBkngS5aafyR+4Ax64XG4X2oWtzxG6WBzuy9Xx4Zdl3Rf7MFGSFLgqkF3nIT+e2X+row+PTUYChEJJTaE6+IJUKK88B/vzawvkYSCOpAoMGNTOcBX3spd+eVbDQ5TQ+yzUXSsmMfga77y+Gzf+o8OVcKegVZO75XiRH+7mkVMDkalsR8uRBY1Bi1ZxMbypxy/XFy8aMlYLa+aFaUjCs7jGDZEah0DoCNO5bDgKLDMMoKRbQF85Wu/8nY5p5llOp4LNCWdQnnJpFMF4EHBVWccM0sG+CruYUpHowX1Kx+nQfAfeOFLRrxdnT35NojRbd1azlAIARIS6A5ByPai18BbYZTpfuCJuEryaOuYPi2RxntrIVtNJvwlpqgY/HKb1GGoeF8jaDW49RMsNagGI01Vozgpduk=}
provider:
  win: azure
