travis:
  secure:
    BINSTAR_TOKEN: iiSpdnaQznWsHrzvYfWDj7gOIFugBPqpInTuccRgKkKx+LNOirnzJJ6H52G7oSW7iqQbi/Nez3reE2qT6qg8WiAgZxe/yXJq/gpSHzzkh2ub4HymfmumPta4nlL/ztazmpHlZ7xPGcjK7VdaM/wfbhT0UiISkGdX62J4a0DJRKvrLrSylteY0ZLBRwOf0U0fQyeneXFTYPwg4+3KtkkLrvwkqAI3JWDGwVV0U69XzVYffh7xGlx1ksLBsCPUm0rVVbxfsFHnjtxghPAYvWPh/o89zuKz7JjCSFoydvOdxyM6WwNBTpR9OJYVJ8SUKeMfUswvOPJ0bD+QXEjY4pVaAiTKkrhyHkR/pmdPM1wsa9fls4ByjkvegiE8pzp7Otg6MtA8WRDHVFneVY0xOA7865Ftnzt42fnug+dv1d4YLDnePwy4+s2dtYowoXitXLa/O3uOU3OwYoAlemq6+ZwhQyKsQwsdCGqCBdRKERnekyYjb1kFHQ9/Lm/vb6sHRUViB+51vawEagzqN917Q/uvKAPqBaMSkjGtaFUCEcSJO2r4JOZwc8N44XoC8+MH7blb/WOpIYuDuhlTjWWeuClVj2aqS+JcXrN7kxnIc2e7yiF+6BD0QmzWKdg0OnJd41KUIDlLXdiykW6doVGVP2lb3PSpw0yDU76zTV6IIQl6BH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
