travis:
  secure:
    BINSTAR_TOKEN: kY35VxdXmL4LW3BSp3IsYsZWds4CGEffPaFLsttd2y6PXXTMBYeZv1GliC6zUnDWEC1ZZEYiUGO79hv9sPTpFQgqCACe9Y3WgMgAvNxK/76KKMkyarAWnhYQD4TR+Ia1hcTvhmUcf0ZRPAKDWXz6jprlk7kzsdvKpIyyBjGXn+HcJks3xxsCF20TE0M/S2bM2LYxh1pZnBrcfSkD/zRR+pcSXkeWv0yuJoM8mzaGNe9vU0qnTgihtbtnBJNOu7qQvnMvLaSlwsXLKXCJMAbeNA6DF+Xova1qlXbSb7iNtky5O7XMrVcyEYqlGrb0FxsLRPFWaan7gLazrC/zUYzh6PxDL9W0BtBRrtYfQhTgAF+NJKegDcs4OAbCHPw1qo24+njlb2gR5pP7KzpUQCs3WqUOT3Yj9+WWHh6Y0gslB4ywy+2L5aD1YKt9rHfD0q6ntJnfY3wEfmvflWF0IJRoVE085qzUOVS64NKA69+BgAITKBkuIe6MJphmZCwCR2AAFYY6m8ypouHGxD6AeqfmjW7VVp6XR8ISZuMWdUxa1n/26bh+GQVI4a6xNAZhBydXRbkl2QDI4NiS4L8JO5/u+NedZOXbi2swnJMaIx/Iu3c2bCMD+3ObyfFyXOR3hYu8/cmdB1jdIF/NBu/VoMaNKUwO+yzpCrePXPbMBchrc7I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
